# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-backend-service
  namespace: ns-app
spec:
  selector:
    app: test-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080