# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection
  namespace: ns-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      containers:
      - name: fraud-detection
        image: dkjt/fraud-service:latest  # Your custom fraud detection image
        ports:
        - containerPort: 4000  # Different from frontend port
        env:
        - name: PORT
          value: "4000"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 5