# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection
  namespace: ns-app
spec:
  selector:
    app: fraud-detection
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000