# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ns-app
spec:
  selector:
    app: backend  # Must match the deployment's pod labels
  ports:
  - name: http
    port: 7777
    targetPort: 7777