# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ns-app
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      app: backend  # Must match the pod template labels
  template:
    metadata:
      labels:
        app: backend  # Must match the selector
    spec:
      containers:
      - name: backend
        image: hashicorp/http-echo
        args: ["-text", "Hello from backend", "-listen", ":7777"]
        ports:
        - containerPort: 7777
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 7777
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 7777
          initialDelaySeconds: 5
          periodSeconds: 5