# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ns-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend  # Matches the pod labels below
  template:
    metadata:
      labels:
        app: frontend  # Must match selector
        tier: frontend  # Additional label
    spec:
      containers:
      - name: frontend
        image: nginxdemos/hello
        ports:
        - containerPort: 80 #6666 #80
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80 #6666 #80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80 #6666 #80
          initialDelaySeconds: 3
          periodSeconds: 3