apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ns-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: dkjt/frontend-static-7766:v1.0.1  # Update version
        imagePullPolicy: Always
        ports:
        - containerPort: 3000  # Nginx port. # Must match Service's targetPort
        #- containerPort: 8080  # Node proxy port
        resources:
          limits:
            memory: "256Mi"  # Increased from 128Mi
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000  # Changed from 7766 to match Nginx
          initialDelaySeconds: 15  # Increased from 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3000  # Changed from 7766 to match Nginx
          initialDelaySeconds: 5
          periodSeconds: 3