# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ns-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend  # Matches the pod labels below
  template:
    metadata:
      labels:
        app: frontend  # Must match selector
        tier: frontend  # Additional label
    spec:
      containers:
      - name: frontend
        #image: nginxdemos/hello   # default to port 80, has 504 time out error error. 
                                  #Has 503 Service Temporarily Unavailable error if port 6667 is used
        # below is working
        # image: hashicorp/http-echo
        # args: ["-text", "this is frontend", "-listen", ":7766"]  # 80 has 504 time out error
        image: dkjt/frontend-static-7766:latest  # Ensure this matches your push
        imagePullPolicy: Always  # Important for updates
        ports:
        - containerPort: 7766    #80 has 504 time out error.
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 7766      #80 has 504 time out error.
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 7766      #80 has 504 time out error.
          initialDelaySeconds: 3
          periodSeconds: 3