apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app2
  namespace: ns-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app2
  template:
    metadata:
      labels:
        app: my-app2
    spec:
      containers:
      - name: frontend
        image: nginxdemos/hello
        ports:
          - containerPort: 80
      - name: backend
        image: kennethreitz/httpbin
        ports:
          - containerPort: 80