apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app2-ingress
  namespace: ns-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: ce-grp-3a-my-app2.sctp-sandbox.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-app2-service
            port:
              number: 80