apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app2-ingress
  namespace: ns-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    #cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Remove if not using TLS
spec:
  # tls is not required if you are not using HTTPS
  # tls:
  # - hosts:
  #   - ce-grp-3a-my-app2.sctp-sandbox.com
  #   secretName: my-app-tls-secret
  rules:
  - host: ce-grp-3a-my-app2.sctp-sandbox.com
    http:
      paths:
      - path: /
        pathType: Prefix  # Matches all subpaths (e.g., /, /home, /contact)
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /api
        pathType: Exact   # Only matches "/api" (not /api/v1, /api/test, etc.)
        backend:
          service:
            name: backend-service
            port:
              number: 7777
      - path: /backend
        pathType: Exact   # Only matches "/backend"
        backend:
          service:
            name: backend-service
            port:
              number: 7777