apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app2-ingress
  namespace: ns-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
spec:
  rules:
  - host: ce-grp-3a-my-app2.sctp-sandbox.com
    http:
      paths:
      - path: /api/detect
        pathType: Exact  # Only matches EXACTLY /api/detect
        backend:
          service:
            name: fraud-detection
            port: 
              number: 4000
      - path: /
        pathType: Prefix  # Catches everything else
        backend:
          service:
            name: frontend-service
            port:
              number: 80