apiVersion: v1
kind: Service
metadata:
  name: my-app2-service
  namespace: ns-app
spec:
  selector:
    app: my-app2
  ports:
    - name: frontend
      port: 80
      targetPort: 80
    - name: backend
      port: 5000
      targetPort: 80