apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ns-app
spec:
  selector:
    app: frontend
  ports:
  - name: http
    port: 80           # external port exposed by the service
    targetPort: 3000   # container port specified in the frontend deployment  
  type: ClusterIP