# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ns-app
spec:
  selector:
    app: frontend  # Matches the deployment's pod labels
  ports:
  - name: http #tcp    #http
    port: 6666       # 80 cannot work. Service exposes this port
    targetPort: 6666 # 80 cannot work. Container listens on this port
  type: ClusterIP  # Explicitly declare service type